### ISSUE TITLE
installing to kubernetes 1.18

### ISSUE THREAD

**Issue by lknite** [pearj/adcs-issuer#1]
I'm new to kustomize.  Think it might be possible to get your install method to work in 1.18?

Here's the output I get:
```
k apply -k config/default
error: rawResources failed to read Resources: Load from path ../crd failed: '../crd' must be a file (got d='/home/lknite/kube/apps/adcs-issuer-system/adcs-issuer/config/crd')
```

**Comment by lknite** [comment]
I may have figured out my own question.  Things look really good if I install kustomize and run:
```
kustomize build ./config/default
```
Working to get adcs-issuer configured and tested ...

**Comment by lknite** [comment]
New error is the following (I've got a caBundle defined in my ClusterAdcsIssuer):
```
level            : error
ts               : 1645139602.16164
logger           : controller-runtime.manager.controller.adcsrequest
msg              : Reconciler error
reconciler group : adcs.certmanager.csf.nokia.com
reconciler kind  : AdcsRequest
name             : demo.dev.its-auto.k-kn7vc
namespace        : demo
error            : CA Bundle required
stacktrace       : sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
                        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253
                   sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
                        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
```

**Comment by pearj** [comment]
Sorry, I missed this. I've setup notifications for myself now.

I think the bundled kustomize support in kubectl tends to be a bit older. Maybe that's why it didn't work unless you use the `kustomize` cli directly. 

I deploy mine via ArgoCD, which I believe uses the `kustomize` cli.

Have you managed to get success?

**Comment by lknite** [comment]
I think so, but in the 1.18 environment the CA has temporarily become unavailable ... so I'm really close but can't get that final satisfaction.  The second I am able to test I'll update here.

**Comment by lknite** [comment]
I switched from using kubectl and kustomize to using argocd and everything installed perfectly via argocd in the 1.18 kubernetes environment.  Everything is working awesome!

**Comment by pearj** [comment]
Great news, I have only tested using the kustomize command directly, good to know that kubectl for 1.18 isn't enough to get it working.
